### ISSUE TITLE
If no statuscode, redirect fails

### ISSUE THREAD

**Issue by jhawlwut** [dwyl/hapi-error#13]
I have a use case where if the user goes (directly) to the root directory of the web app, and for whatever reason the authentication fails (401), it should redirect to the /login page; through some debugging, I found that if there is no previous .statuscode available, the redirect fails entirely.

I'm referring to this specific line:
https://github.com/dwyl/hapi-error/blob/master/lib/index.js#L16

``` javascript
+ '?redirect=' + request.url.path).code(statusCode);
```

When you remove .code(statusCode), the redirect works fine.

**Comment by nelsonic** [comment]
Hi @jhawlwut thanks for _using_ `hapi-error` and for taking the time to give us feedback!! 👍 

So, if I _understand_ correctly, auth fails but is not throwing a `boom` error with a valid `statusCode` ...? 😕 

Are you able to share a bit more code so we can help diagnose the issue?
(_and so we can write a regression test and fix it!_)

![hapi-error-code-sample](https://cloud.githubusercontent.com/assets/194400/17937864/843245dc-6a1b-11e6-810a-6895aaacd69a.png)

Would adding a check for `statusCode` on [Line 14](https://github.com/dwyl/hapi-error/blob/793b790aa9c0bc594bdbac6b5d78c6033184c0e7/lib/index.js#L14) solve the issue?
_Technically_ we should not _get_ to [Line 16](https://github.com/dwyl/hapi-error/blob/793b790aa9c0bc594bdbac6b5d78c6033184c0e7/lib/index.js#L16) if `statusCode` is unset... 😖 

> What is the **_desired behaviour**_? (_and do you have time to write a PR with a test? thanks!_)

**Comment by jhawlwut** [comment]
So it's interesting, a little more digging reveals it _is_ returning a statusCode, in this instance 401, but if I attach the .code to the end of the redirect, it just returns the statuscode and doesn't redirect. Here's my workflow:

Going directly to the "/" root which would normally return the index template for the app, but since the JWT isn't valid (this is expected), hapi-error catches the 401 properly but when the .status is attached to the redirect, it simply stays on "/" and returns the 401 with no redirect. When I remove the .status, the redirect works as it should. 

I'm not sure I need to pass the previous status (401) back to the login page as the redirect will suffice once the user is re-authenticated. Perhaps a boolean option would suffice which allows you to remove the .status; or just remove it altogether? If the user is being redirected the login page, isn't the 401 already assumed since it was caught?

**Comment by jhawlwut** [comment]
btw, super fast response and diagnosis on this... 💰

**Comment by nelsonic** [comment]
@jhawlwut yeah, for the `/login` example the `401` status code can _safely_ be assumed. 
The reason we put the `.code(statusCode);` at the end of the `redirect()` was for _other_ errors.

> But on _further reflection_, how many situations _are_ we going to want to redirect?
> (Most other types of error will result in displaying an error _page_ with helpful info...)

@naazy / @rjmk / @des-des / @alanshaw  your thoughts on this would be _much appreciated_

**Comment by jhawlwut** [comment]
IMO, if the purpose is to redirect to a login screen, which this seems intended to do, there is no need for the .status since the /login screen is going to need to be 200 anyways. Seems like a quick fix if you all agree.

**Comment by nelsonic** [comment]
@jhawlwut wish there was a way of passing back the `statusCode` _and_ re-directing ... 😞

**Comment by jhawlwut** [comment]
@nelsonic what if you just passed it as a custom param in the header?

**Comment by nelsonic** [comment]
Hmm... good question. let's try it.

**Comment by jhawlwut** [comment]
Do you want to do it or I can just submit from my PR (once I fix the test); what do you have in mind as what the header should look like?

**Comment by rjmk** [comment]
I think redirecting on a 401 is not to the HTTP spec

**Comment by nelsonic** [comment]
@rjmk thanks rescuing us! 

On further investigation, I made two `curl` requests to endpoints on Twitter & GitHub respectively which require auth:

`curl -v https://twitter.com/i/notifications` 

![curl-twitter-302](https://cloud.githubusercontent.com/assets/194400/17939438/910d331e-6a22-11e6-8317-dfad95e10133.png)

`curl -v https://github.com/settings/profile`
![curl-github-302](https://cloud.githubusercontent.com/assets/194400/17939948/b6f4d396-6a24-11e6-880b-5b45ce009235.png)

I'm _confident_ that the engineers at these two companies will have followed "_best practice_".
So... let's _drop_ the `.code(statusCode)`, update the test and ship a new version! 👍

**Comment by nelsonic** [comment]
@jhawlwut > https://github.com/dwyl/hapi-error/pull/14#issuecomment-242138032
(_if you have time to update the test we can get a new version of the plugin/module published and you can get on with your work..._ 😉 )

**Comment by jhawlwut** [comment]
yes will do, tying up something else, i'll have it shortly
