### ISSUE TITLE
"Accept" Header Priority

### ISSUE THREAD

**Issue by jhawlwut** [dwyl/hapi-error#17]
While working with the redirect, I noticed if I passed "Accept" with json from the client, it would redirect and return 200 when I just wanted the original (in this case 401) response from the API. I believe the priority should be given to the "accept" header, followed by the redirect, ending with the error_template.

Redirect works as expected for browser windows, but we shouldn't be catching every 401 response and redirecting; I've already completed the fix and will make a PR.

**Comment by nelsonic** [comment]
@jhawlwut yeah, I (_also_) thought the API usecase would want the original response (not redirect). thanks for confirming. merged. 👍
