### ISSUE TITLE
Is it possible to pass extra handlebar props to error_template.html?

### ISSUE THREAD

**Issue by naazy** [dwyl/hapi-error#19]
Or are we currently limited by errorTitle, statusCode and errorMessage? If not, am I okay to make a PR?

**Comment by nelsonic** [comment]
@naazy _good question_! which other properties/values would you _like_ to be able to define / pass in?

**Comment by naazy** [comment]
@nelsonic Ideally we want the flexibility to add any props to the default handlebar props. We would mainly be using it to pass the user's email address and name to our header partial and also relevant menu items.

**Comment by nelsonic** [comment]
@naazy ok, cool. sounds like we can _evolve_ the plugin and make it more general-purpose (_and thus more useful to other people in the process_) 
so the question is: how are we going to _pass_ the additional properties into the plugin?

My reading of the `Hoek.assert()` API https://github.com/hapijs/hoek/blob/master/API.md#assertcondition-message suggests we can pass an `Object` in as the message, let's try that.

> Please review/merge: https://github.com/dwyl/hapi-error/pull/16 so we have a fresh place to start from. (_thanks!_)

**Comment by naazy** [comment]
@nelsonic - I've had a play around and any objects passed in as the message are stringified. We can JSON.parse them and then use them as handlebar props. I will try to get this into a PR

**Comment by nelsonic** [comment]
@naazy sweet! if we `try` to `JSON.parse` and find that the message is a _stringified_ `Object` then we can [`Object.assign`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) it to the Object that gets passed to the [`reply.view`](https://github.com/dwyl/hapi-error/blob/8afdf95503996e0ebc3348a32dc70e183ab34016/lib/index.js#L42)

**Comment by naazy** [comment]
I believe I have now got this to work but have somehow managed to break the redirect tests (should probably not have actually put a fix in the commit message - sorry!). Can't figure out how I've managed to do this but will have a look again tomorrow with a fresh pair of eyes ❄️ 👀
