### ISSUE TITLE
Uncaught errors in route handler are missing from the debug log

### ISSUE THREAD

**Issue by cristinecula** [dwyl/hapi-error#22]
I really love this plugin. Having beautiful error pages is very important for a great user experience.

Unfortunately it seems it interferes with error logging. If an error is thrown in a route handler, the plugin somehow makes hapi think the error was handled, instead of logging an uncaught error. Of course, this results in broken functionality and no log of the error.

```
    server.route({
        method: 'GET',
        path: '/throw',
        handler: (request, reply) => {

            throw new Error('AAAAA!');
        }
    });
```

Normal output:

```
npm start

> widgetic-shopify@1.0.0 start /home/cristi/Projects/widgetic/integrations/shopify
> node index.js

Server running at: http://grumpy:3000
Debug: internal, implementation, error
    Error: Uncaught error: AAAAA!
    at handler (/home/cristi/Projects/widgetic/integrations/shopify/lib/modules/backend/index.js:72:19)
    ...
^C
```

With hapi-error:

```
npm start

> widgetic-shopify@1.0.0 start /home/cristi/Projects/widgetic/integrations/shopify
> node index.js


Server running at: http://grumpy:3000
^C
```

I would have loved to submit a pull request with a fix, but this is my first project using hapi and I have little experience with how hapi handles errors.

**Comment by nelsonic** [comment]
Hi @cristinecula thanks _very_ much for creating this issue (_and welcome to DWYL!_)
We need to add an _on-uncaught-exception_ handler to catch these types of errors. 
Maybe we can "_just_" use https://github.com/hapijs/poop ?

relates to #8

**Comment by nelsonic** [comment]
@cristinecula / @naazy 
Inside `lib/index.js` I've added a `server.log` which will _ensure_ that **_all**_ errors are logged.
this will _only_ be visible if you are using `good` for logging. here the sample output:
![hapi-error-log](https://cloud.githubusercontent.com/assets/194400/19013932/f2471060-87d6-11e6-980a-d7210c9fea7e.png)
