### ISSUE TITLE
Cleaning the error message

### ISSUE THREAD

**Issue by jrans** [dwyl/hapi-error#31]
[this](https://github.com/dwyl/hapi-error/blob/master/lib/index.js#L92) switch statement overwrites error messages for certain status codes. 

I feel that's not this plugin's remit. People should handle these messages/provide defaults in their `error_template` view but not at this layer. 

I see it simplifies the message but sometimes you might to keep that information, parse it in someway?

Maybe its an opt out feature but certainly needs to be mentioned that you are handling `400` `401` `404` errors and not others?

**Comment by nelsonic** [comment]
@jrans I _agree_. do you want to submit a PR updating it? 
(_we will need to release a new version as it will "break" backward compatibility, but I agree, we should remove the `switch` and let people have control of their error messages!_)

**Comment by jrans** [comment]
@nelsonic Ok will get it done!

**Comment by jrans** [comment]
@nelsonic Before i start the work just wanted to see which approach you'd prefer:
- Like the redirect options provide option to handle each code (and have a default which is try and parse as json). 
- Remove all together?
  - Let them handle everything.  or
  - parse if json

Thinking the first option may be nice as could say for all 500s do ( ) =>  'Sorry our bad', while 400s could be more illuminating

**Comment by nelsonic** [comment]
@jrans my original reasoning was to set better error messages than the default error messages for each type of status code. https://github.com/dwyl/hapi-error#what 
Yes, we could supply a configuration object similar to the re-direct one. 
It _might_ even be an idea to _consider_ making it a _language_ file so we can show error messages based on the user-agent's locale ... ?

**Comment by jrans** [comment]
ok glad you agree. Thats a nice idea, perhaps we could pass the original request object as another argument to these message handlers so people can do this. But no having the option to use thought about defaults is a huge plus. We could perhaps decide on favourite messages, provide the defaults whilst letting them always customise and finally show even more examples of sets of responses in the example folder.

**Comment by nelsonic** [comment]
fixed by @jrans in `hapi-error@1.5.0` (_New/Latest Version on NPM_) 🎉
