### ISSUE TITLE
add ability to configure templateName in plugin config

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-error#39]
some people would _prefer_ to be able to _configure_ the name of the `error_template` ... https://github.com/dwyl/hapi-error/pull/38

**Comment by calmdev** [comment]
@nelsonic see c59ce5739741c9a2c1ad8c87ad99eb750d9405bc

**Comment by nelsonic** [comment]
@calmdev thanks _very_ much for adding that. 
(_we usually prefer to have Pull Requests where at least one person reviews new code/docs before being merged into `master` - rather than committing directly to `master` but you didn't know and I didn't make it clear, so no harm_)

**Comment by nelsonic** [comment]
@calmdev latest version `hapi-error@1.6.0` on NPM has your new feature. 🎉

**Comment by calmdev** [comment]
Awesome thanks @nelsonic

**Comment by calmdev** [comment]
Sorry about the commit directly to master. Not being able to fork was a different work flow for me (github said I already had a fork and this was it, hadn't seen that before) and I wasn't expecting the commit to master to work. Next time I'll make sure it's sent as a PR though.
