### ISSUE TITLE
Stack trace not logged

### ISSUE THREAD

**Issue by jay-meister** [dwyl/hapi-error#43]
In our application, we are using hapi-error, Hoek and good-console. However when we Hoek.assert an error, we do not get the error stack trace logged to the console.  This is the most useful part of the error for us in understanding what it was that went wrong.

In my local node modules i have adapted the debug object that gets logged to include the stack trace: 

```js
  debug = {
        error: res.stack,
        method: req.method, // e.g GET/POST
        url: request.url.path, // the path the person requested
        headers: request.raw.req.headers, // all HTTP Headers
        info: request.info, // all additional request info (useful for debug)
        auth: request.auth, // any authentication details e.g. the decoded JWT
        email: request.auth.credentials && request.auth.credentials.email
          ? request.auth.credentials.email : '', // see: https://git.io/vPZBK
        payload: request.payload, // the complete request payload received
        response: res.output.payload // response before error intercepted
      };
```

This allows me to see the trace in the logged error:
```js
170106/122308.616, [log,error] data: {"error":"Error: Uncaught error: database error error: value too long for type character varying(200)\n
    at Object.exports.assert (/Users/jmurphy/web/ce100-app/node_modules/hoek/lib/index.js:736:11)\n
    at /Users/jmurphy/web/ce100-app/server/handlers/orgs/edit-org.js:13:10\n
    at /Users/jmurphy/web/ce100-app/node_modules/pg-people/lib/index.js:111:16\n
    at Query.<anonymous> (/Users/jmurphy/web/ce100-app/node_modules/pg-helpers/lib/query.js:16:14)\n

    at bound (domain.js:280:14)\n
    at Query.runBound (domain.js:293:12)\n
    at Query.handleError (/Users/jmurphy/web/ce100-app/node_modules/pg/lib/query.js:129:17)\n    at Connection.<anonymous> (/Users/jmurphy/web/ce100-app/node_modules/pg/lib/client.js:180:26)\n
    at emitOne (events.js:96:13)\n
    at Connection.emit (events.js:188:7)"
...
```

Is there a reason we do not include the stack trace in the logged error? Is it desired functionality (i can PR) or does it already exist and I have missed it?

**Comment by nelsonic** [comment]
@JMurphyWeb given that you are working on an open source codebase would you mind linking to the line of code where you are attempting to log the stack trace and not seeing what you need? (_please/thanks!_)

**Comment by jay-meister** [comment]
@nelsonic 

Sure: https://github.com/emfoundation/ce100-app/blob/master/server/handlers/orgs/edit-org.js#L12

Locally i just changed that line to:
```js
    Hoek.assert(!error, error);
```
to check whether that would change anything, but it didn't.

**Comment by ghormann** [comment]
@nelsonic 
I'm having a simular problem to the OP on this issue..  I was looking at #22 and noticed in that testing that neither the error message ('AAAAAA!) nor the full stack trace of the error were logged even with good was enabled. 

I was expecting a full stack trace in addtion to the same information logged in the screenshot attached to #22 .   Are my expectations too high? Have a better suggestion for making sure the stack traces are logged?

**Comment by jay-meister** [comment]
I am happy to make a PR if @nelsonic agrees. Planned implementation is covered in the description.

**Comment by nelsonic** [comment]
@JMurphyWeb go for it! this would be a _great_ improvement to stack tracing! thanks! ❤️

**Comment by jay-meister** [comment]
@ghormann did you `npm update` to get new package version with stack trace logging?

**Comment by ghormann** [comment]
@JMurphyWeb I've updated to 1.7.0 and I see the stack trace being logged.   Thanks for the quick patch.
