### ISSUE TITLE
Redirect as a function

### ISSUE THREAD

**Issue by kadon** [dwyl/hapi-error#47]
Hello, I am using hapi-error plugin and I am facing a problem, I'd like to form my url (redirect) dinamically based on some configurations I have in the Request object, my question is, could be it possible to pass a function to `redirect` property? the same way we can pass a function to `message` property.

**Comment by nelsonic** [comment]
@kadon good question! the answer is _yes_ it's _technically_ possible. do you have time to make a PR to add this functionality?

**Comment by DavidHavl** [comment]
Just published a PR for this.
https://github.com/dwyl/hapi-error/pull/55

**Comment by nelsonic** [comment]
@kadon this feature is available in `2.3.0` thanks again for requesting it. 👍
