### ISSUE TITLE
Should we Add Option to Re-direct on 401 (Auth Error) ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-error#5]
Should we have the ability to define a `redirectRoute` in the `options` passed into the Plugin?
such that when a `401` error (_Authentication Error_) occurs, people are automatically re-directed to `/login` ?

relates to: https://github.com/dwyl/hapi-auth-jwt2/issues/162

**Comment by nelsonic** [comment]
If enough people _use_ this module and tell us they want the `redirect` feature we can implement it... 👍

**Comment by naazy** [comment]
I think this would be a good enhancement. I'm happy to have a stab at this!

**Comment by nelsonic** [comment]
Oh, cool! Yes, go for it! 
We'll need to have a separate test file with a new server and a "/login" endpoint so the re-direct works.
Ping me if you need anything! 👍 

![dilbert-404-error](https://cloud.githubusercontent.com/assets/194400/17856406/53feeee4-6875-11e6-8480-d493906f6aa1.png)

**Comment by nelsonic** [comment]
@naazy I think it's as simple as setting:

``` js
const custom = {
    "401": {
        "redirect": "/login"
    }
}
server.register([{ register: require('hapi-error'), options: custom }, require('vision')], function (err) {
... etc.
```
