### ISSUE TITLE
Custom error messages not working when status code != 500

### ISSUE THREAD

**Issue by cmaas** [dwyl/hapi-error#53]
I noticed that a custom error message apparently is only passed to the template when called with a `500` status code like so:

```
reply(Boom.badImplementation('Test'));
```

It doesn't work like so: 

```
reply(Boom.notFound('Test'));
```

And this way, it doesn't work either:

```
request.handleError(true, "Test")
```

So, two issues:

1. The docs don't make it clear how to display a custom error message to the end user. The docs also don't match the example code. I don't want to pre-configure an error message, but decide in my controller/route which error to show. Think of this as `Sorry, TodoList not found` or `Sorry, TodoItem not found`.
2. `handleError` apparently doesn't show the custom error message, although the docs say it should. Furthermore, `handleError` doesn't seem to allow other status codes than 500. But this is probably a separate issue.

**Comment by nelsonic** [comment]
@cmaas _thank you_ for opening this issue! 
we have a tests for `400`
https://github.com/dwyl/hapi-error/blob/459435162f59f6796ff3aaee19f4eee6a09e77ff/test/index.test.js#L169
and `404`:
https://github.com/dwyl/hapi-error/blob/459435162f59f6796ff3aaee19f4eee6a09e77ff/test/index.test.js#L105

However you are _correct_ these are not explicitly "_throwing_" a `Boom.notFound()` ...
We could consider adding a test/route that _explicitly_ throw Boom errors. 🤔

**Comment by cmaas** [comment]
@nelsonic Not sure how these tests help to actually test whether a custom error message is added to the template 🤔

**Comment by nelsonic** [comment]
Closing due to significant changes in `hapi-error` for Hapi v.17 meaning this should no longer be an issue.
Please re-open if still a problem.
Thanks! ☀️
