### ISSUE TITLE
Needs updating to work with Hapi 17+

### ISSUE THREAD

**Issue by brabster** [dwyl/hapi-error#54]
The plugin contract was subject to breaking changes in v17 https://github.com/hapijs/hapi/issues/3658

This plugin doesn't work with 17+.

**Comment by steevhise** [comment]
Is anyone working on a port to 17?

**Comment by iteles** [comment]
@steevhise No one is assigned to this issue so no one has taken this on yet. 
None of our existing projects using this module have upgraded to v17 yet so we haven't been able to make the time to update this yet ourselves either!

Feel free to take on the challenge if you wish 😊

**Comment by tejzpr** [comment]
@iteles @nelsonic I have created a [PR](https://github.com/dwyl/hapi-error/pull/56) for Hapi.js v17 support. Please have a look at it. I have bumped the major version to v2.0.0 because the code does not include backward compatibility for Hapi.js < v17 & NodeJs < v8.

**Comment by tejzpr** [comment]
Should I be releasing this [PR](https://github.com/dwyl/hapi-error/pull/56) as a new NPM package?

**Comment by cmaas** [comment]
@nelsonic @iteles Please approve the PR if possible. Would be a shame if this goes to waste

**Comment by nelsonic** [comment]
@cmaas thanks for the "ping" (reminder) of the PR.
the _reason_ the package has not yet been published is that test coverage is 94% (_i.e. incomplete_):
![image](https://user-images.githubusercontent.com/194400/44943731-a4398700-adcb-11e8-84da-412ace6fd61f.png)
I've merged the PR and am working on getting 100% test coverage.

**Comment by iteles** [comment]
New version 2.0.1 is available on NPM compatible with Hapi v17 thanks to @tejzpr 🎉
