### ISSUE TITLE
TypeScript error: Statements are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by mfellner** [dwyl/hapi-error#61]
### Description
There's a problem with the type definitions that leads to the following error:
```
Error at node_modules/hapi-error/index.d.ts:15:2: Statements are not allowed in ambient contexts.
```
This is caused by a semicolon in the namespace declaration: `};`.

### Steps to reproduce
1. `npm install typescript@3.0.3`
2. `npm install hapi-error@2.0.1`

**Comment by nelsonic** [comment]
@mfellner _thank you_ for reporting (_and fixing!_) this issue. 🥇

**Comment by nelsonic** [comment]
`hapi-error@2.1.0` on NPM contains your fix. thanks again! ❤️
