### ISSUE TITLE
Publish newest version to npm

### ISSUE THREAD

**Issue by grahamnordstrom** [dwyl/hapi-error#66]
Looks like hapi-error is still showing up as version 2.1.0 on npmjs.com
See [here](https://www.npmjs.com/package/hapi-error).
I noticed that the tag has been successfully pushed [here](https://github.com/dwyl/hapi-error/releases/tag/v2.2.0), but no joy on npm.
Using the direct url to the tarball as a work around for now.

**Comment by nelsonic** [comment]
@grahamnordstrom, thanks for alerting us to this. This is very bizarre ...

# `Cannot publish over previously published version "2.2.0". : hapi-error`
![image](https://user-images.githubusercontent.com/194400/58744336-3cd36500-8439-11e9-809d-56e29e040791.png)

https://www.npmjs.com/package/hapi-error
![image](https://user-images.githubusercontent.com/194400/58751325-104d3680-8495-11e9-8831-a69dd09b1588.png)


Looks like NPM not accepting the publish.
May need to skip version 2.2.0 and publish a patch release.

**Comment by Hydrock** [comment]
@nelsonic  Please, make a new release - I think you can just skip the problematic version
I tried to ask a question to tech support - will see

**Comment by nelsonic** [comment]
@Hydrock I will publish a new version as soon as #72 is reviewed/merged by @iteles 👍

**Comment by iteles** [comment]
@nelsonic Thanks for getting the test coverage back up to 💯 👍 
Should be ready to publish now.

**Comment by nelsonic** [comment]
`hapi-error@2.2.2` now available on NPM includes the bugfix made by @Hydrock in #69 👍

**Comment by Hydrock** [comment]
@nelsonic @iteles Thank you very much!

**Comment by grahamnordstrom** [comment]
@nelsonic Thanks for following up and getting this published!

**Comment by nelsonic** [comment]
@grahamnordstrom thank @Hydrock for fixing the tests #68 and fixing the redirect issue #70 🙌 
Publishing is the _easy_ part. It's the _least_ I can do. 
Glad you still find the module useful. 👍
