### ISSUE TITLE
undefined in the redirect parameters

### ISSUE THREAD

**Issue by Hydrock** [dwyl/hapi-error#69]
![image](https://user-images.githubusercontent.com/20814779/73209984-61afe180-415a-11ea-9300-77d317383d29.png)

When I try to go to /cabinet I am redirected to /auth
It's correts - just mu app logic, but I see **undefined** in the search bar

If we try ещ to see hapi-error code, we will see:

```
if (config.statusCodes[statusCode]
    && config.statusCodes[statusCode].redirect) {
    return reply.redirect(config.statusCodes[statusCode].redirect
    + '?redirect=' + request.url.path);
}
```
request.url.path is used her - trying to log

```
request.url URL {
  href: 'http://localhost:3000/cabinet',
  origin: 'http://localhost:3000',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'localhost:3000',
  hostname: 'localhost',
  port: '3000',
  pathname: '/cabinet',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

there is no path key here

I khow that Hapi uses a url ( [https://github.com/defunctzombie/node-url#readme](https://github.com/defunctzombie/node-url#readme) )

look at the keys

**pathname**: The path section of the URL, that comes after the host and before the query, including the initial slash if present.
**path**: Concatenation of pathname and search.

I don't know why my URL object is missing the **path** key

Maybe do something similar:
```
+ '?redirect=' + (request.url.path || request.url.pathname) );
```

I would also like to disable the parameters in the address bar (I don't need them) when redirecting

i used node v12.13.0

**Comment by Hydrock** [comment]
I understand. Hapi server used Node URL.

if we look at the old documentation ([v4](https://nodejs.org/docs/latest-v4.x/api/url.html)) we will see the **path** key

But in earlier versions of NodeJS ([v6](https://nodejs.org/docs/latest-v6.x/api/url.html)) - the key **path** is missing

I'll try something like this:
```
+ '?redirect=' + (request.url.pathname + request.url.search)
```

**search**: The 'query string' portion of the URL, including the leading question mark.
Example: '?query=string'
**pathname**: The path section of the URL, that comes after the host and before the query, including the initial slash if present. No decoding is performed.
Example: '/p/a/t/h'

These parameters are present in the old version of NodeJS

**Comment by Hydrock** [comment]
I fixed it - a happy time for a new release

**Comment by nelsonic** [comment]
Fixed by #70 ✅

**Comment by Hydrock** [comment]
> Fixed by #70 ✅

thanks

**Comment by nelsonic** [comment]
@Hydrock please confirm v2.2.2 is working as expected in your project. 👍

**Comment by Hydrock** [comment]
> @Hydrock please confirm v2.2.2 is working as expected in your project. 👍

yes, all works good
now i see correct redirect parameter and redirect works like function too
