### ISSUE TITLE
Wrong hapi version import in typescript file

### ISSUE THREAD

**Issue by paulrobello** [dwyl/hapi-error#75]
index.d.ts imports from 'hapi' instead of '@hapi/hapi' which is causing problems with handleError not being found on the Request class.
using
"@hapi/hapi": "^20.0.3"
"hapi-error": "^2.3.0"

**Comment by tejzpr** [comment]
@nelsonic I'll update this after #84 is merged as changes for this fix should be released as a major version update.

**Comment by nelsonic** [comment]
Fixed by #85 ✅ 
Thanks again @tejzpr
