### ISSUE TITLE
Logging errors

### ISSUE THREAD

**Issue by naazy** [dwyl/hapi-error#8]
When errors are thrown by Hoek, debugging can be quite difficult as it is not always obvious where the error was thrown. Giving the developer the option to log the error in the console would be useful.

**Comment by naazy** [comment]
Actually, I've just seen that we can access the errors via request.response 👍

**Comment by naazy** [comment]
Re-opening because have decided that this would be useful again

**Comment by nelsonic** [comment]
@naazy totally agree! this would be a _great_ addition. if you have time to add some detail for how you would like the feature to work and add some pseudo/example code, please go for it! 👍

**Comment by nelsonic** [comment]
@naazy what about using `good` https://github.com/hapijs/good to log errors?

**Comment by cristinecula** [comment]
I have used good along with hapi-error and it works like a charm, save for #22. You have the best of both worlds: pretty, informative error pages for the users and comprehensive logging for devops.
